/* BarTab: lokale administratie voor een bar. Bedragen worden altijd als hele centen bewaard. */
const STORAGE_KEY = 'bartab-state-v1';
const APP_VERSION = '1.1.1'; // Verhoog dit bij iedere gepushte release.
const ADMIN_PASSWORD = 'bier123'; // Wijzig dit wachtwoord hier als dat later nodig is.
const DEFAULT_DRINKS = [
  { id: 'beer', name: 'Bier', price: 300, fridgeStock: 0, cellarStock: 0, fridgeCapacity: 0 }, { id: 'wine', name: 'Wijn', price: 450, fridgeStock: 0, cellarStock: 0, fridgeCapacity: 0 },
  { id: 'soft', name: 'Frisdrank', price: 275, fridgeStock: 0, cellarStock: 0, fridgeCapacity: 0 }, { id: 'water', name: 'Water', price: 200, fridgeStock: 0, cellarStock: 0, fridgeCapacity: 0 },
  { id: 'coffee', name: 'Koffie', price: 250, fridgeStock: 0, cellarStock: 0, fridgeCapacity: 0 }, { id: 'special', name: 'Speciaalbier', price: 500, fridgeStock: 0, cellarStock: 0, fridgeCapacity: 0 }
];
let adminUnlocked = false;
let adminUnlockTimer = null;
let adminIdleTimer = null;
let activeGroupId = null;
let groupLocked = false;
let modalMode = null;
let modalData = {};
let toastTimer;
let lowStockTimer;
let activeStatsCustomerId = 'all';
const $ = (selector) => document.querySelector(selector);
const formatMoney = (cents) => new Intl.NumberFormat('nl-NL', { style: 'currency', currency: 'EUR' }).format((cents || 0) / 100);
const makeId = (prefix) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
const todayStart = () => { const date = new Date(); date.setHours(0, 0, 0, 0); return date.getTime(); };
const escapeHtml = (value) => { const div = document.createElement('div'); div.textContent = value ?? ''; return div.innerHTML; };

function repairMojibake(value) { if (typeof value !== 'string') return value; return value.replaceAll('â€º', '›').replaceAll('âœŽ', '✎').replaceAll('Ã—', '×').replaceAll('âœ“', '✓').replaceAll('âœ”', '✔').replaceAll('â†’', '→').replaceAll('â†', '←'); }
function normalizeDrink(drink) { const legacyStock = Number.isFinite(drink.stock) ? drink.stock : 0; return { ...drink, name: repairMojibake(drink.name), fridgeStock: Number.isFinite(drink.fridgeStock) ? drink.fridgeStock : legacyStock, cellarStock: Number.isFinite(drink.cellarStock) ? drink.cellarStock : 0, fridgeCapacity: Number.isFinite(drink.fridgeCapacity) ? drink.fridgeCapacity : legacyStock, refillBaseline: Number.isFinite(drink.refillBaseline) ? drink.refillBaseline : legacyStock }; }
function loadState() {
  try {
    const saved = JSON.parse(localStorage.getItem(STORAGE_KEY));
    if (saved && Array.isArray(saved.drinks)) {
      const next = { drinks: saved.drinks.map(normalizeDrink), customers: (saved.customers || []).map((customer) => ({ ...customer, name: repairMojibake(customer.name) })), groups: (saved.groups || []).map((group) => ({ ...group, name: repairMojibake(group.name) })), history: (saved.history || []).map((entry) => ({ ...entry, customerName: repairMojibake(entry.customerName), drinkName: repairMojibake(entry.drinkName) })), tabs: saved.tabs || [], lastRefillAt: saved.lastRefillAt || null };
      migrateLegacyTabs(next); ensureHomeCustomer(next); return next;
    }
  } catch (error) { console.warn('Opgeslagen BarTab-data kon niet worden gelezen.', error); }
  const next = { drinks: DEFAULT_DRINKS.map(normalizeDrink), customers: [], groups: [], history: [], tabs: [], lastRefillAt: null }; ensureHomeCustomer(next); return next;
}
function migrateLegacyTabs(next) {
  if (!next.tabs.length || next.customers.length) return;
  next.tabs.forEach((tab) => { const customer = { id: makeId('customer'), name: tab.name, balance: 0, lastOrderAt: tab.createdAt || 0 }; next.customers.push(customer); (tab.items || []).forEach((item) => { const amount = item.price * item.quantity; customer.balance -= amount; next.history.push({ id: makeId('history'), type: 'order', customerId: customer.id, customerName: customer.name, drinkName: item.name, quantity: item.quantity, amount, createdAt: tab.createdAt || Date.now() }); }); });
}
function ensureHomeCustomer(next) { if (!next.customers.some((customer) => customer.name.toLowerCase() === 'thuis')) next.customers.unshift({ id: 'home-customer', name: 'Thuis', balance: 0, lastOrderAt: 0 }); }
let state = loadState();
function saveState() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function showView(viewId) { document.querySelectorAll('.view').forEach((view) => view.classList.toggle('is-hidden', view.id !== `${viewId}-view` && view.id !== viewId)); }
function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('is-visible'); clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.remove('is-visible'), 2400); }
function getCustomer(id) { return state.customers.find((customer) => customer.id === id); }
function getGroup(id) { return state.groups.find((group) => group.id === id); }
function isHome(customer) { return customer.name.toLowerCase() === 'thuis'; }
function parsePrice(value) { const number = Number.parseFloat(String(value).trim().replace(',', '.')); return Number.isFinite(number) && number > 0 ? Math.round(number * 100) : null; }
function parseCount(value) { const number = Number.parseInt(value, 10); return Number.isFinite(number) && number >= 0 ? number : 0; }
function getHistoryLabel(entry) { return entry.type === 'deposit' ? 'Bijstorting' : entry.type === 'withdrawal' ? 'Afhaling' : entry.drinkName; }
function getHistorySign(entry) { return entry.type === 'deposit' ? '+' : '-'; }
function getConsumedSinceRefill(drink) { const start = state.lastRefillAt || 0; return state.history.filter((entry) => entry.type === 'order' && entry.drinkName === drink.name && entry.createdAt >= start).reduce((total, entry) => total + (Number.isFinite(entry.quantity) ? entry.quantity : 0), 0); }
function getRefillAmount(drink) { return Math.min(Math.max(0, drink.fridgeCapacity - drink.fridgeStock), drink.cellarStock); }
function openModal(mode, data = {}) { modalMode = mode; modalData = data; $('#modal').classList.remove('is-hidden'); $('#modal-error').textContent = ''; const fields = $('#modal-fields'); let title = 'BarTab'; let content = '';
  if (mode === 'password') { title = 'Admin toegang'; content = '<label for="modal-password">Wachtwoord</label><input id="modal-password" type="password" autocomplete="current-password" required>'; }
  if (mode === 'customer-order') { title = `Bestelling voor ${escapeHtml(data.customer.name)}`; content = `<div class="order-picker">${state.drinks.map((drink) => `<div class="picker-row"><div><strong>${escapeHtml(drink.name)}</strong><span>${formatMoney(drink.price)}</span></div><div class="quantity-controls"><button type="button" data-picker="down" data-drink-id="${drink.id}">-</button><span id="pick-${drink.id}">0</span><button type="button" data-picker="up" data-drink-id="${drink.id}">+</button></div></div>`).join('')}</div>`; }
  if (mode === 'customer-history') { title = `Geschiedenis: ${escapeHtml(data.customer.name)}`; const entries = state.history.filter((entry) => entry.customerId === data.customer.id).sort((a, b) => b.createdAt - a.createdAt); content = entries.length ? `<div class="admin-list">${entries.map((entry) => `<div class="history-row"><div><strong>${escapeHtml(getHistoryLabel(entry))}</strong><span>${entry.type === 'deposit' ? 'Saldo toegevoegd' : entry.type === 'withdrawal' ? 'Saldo afgehaald' : `${entry.quantity} x ${escapeHtml(entry.drinkName)}`}</span></div><time>${new Date(entry.createdAt).toLocaleString('nl-NL')}</time><b class="${entry.type === 'deposit' ? 'positive' : 'negative'}">${getHistorySign(entry)}${formatMoney(entry.amount)}</b></div>`).join('')}</div>` : '<p class="muted">Nog geen geschiedenis voor deze klant.</p>'; }
  if (mode === 'drink') { title = data.drink ? 'Drank bewerken' : 'Drank toevoegen'; content = `<label for="modal-name">Naam</label><input id="modal-name" required maxlength="40" value="${escapeHtml(data.drink?.name || '')}"><label for="modal-price">Prijs</label><input id="modal-price" required inputmode="decimal" placeholder="0,00" value="${data.drink ? (data.drink.price / 100).toFixed(2).replace('.', ',') : ''}">`; }
  if (mode === 'customer') { title = data.customer ? 'Klant bewerken' : 'Klant toevoegen'; content = `<label for="modal-name">Naam</label><input id="modal-name" required maxlength="40" value="${escapeHtml(data.customer?.name || '')}">`; }
  if (mode === 'deposit' || mode === 'withdrawal') { title = `${mode === 'deposit' ? 'Bijstorting' : 'Bedrag afhalen'} voor ${escapeHtml(data.customer.name)}`; content = '<label for="modal-price">Bedrag</label><input id="modal-price" required inputmode="decimal" placeholder="0,00">'; }
  if (mode === 'group') { title = data.group ? 'Groep bewerken' : 'Nieuwe groep'; content = `<label for="modal-name">Groepsnaam</label><input id="modal-name" required maxlength="50" value="${escapeHtml(data.group?.name || '')}">`; }
  if (mode === 'group-members') { title = `Klanten in ${escapeHtml(data.group.name)}`; content = `<div class="checkbox-list">${state.customers.filter((customer) => !isHome(customer)).map((customer) => `<label class="check-row"><input type="checkbox" data-member-id="${customer.id}" ${data.group.customerIds.includes(customer.id) ? 'checked' : ''}>${escapeHtml(customer.name)}</label>`).join('')}</div>`; }
  if (mode === 'refill') { title = 'Hervulling'; const rows = state.drinks.filter((drink) => getRefillAmount(drink) > 0).map((drink) => `<label class="refill-row"><input type="checkbox" data-refill-id="${drink.id}"><span><strong>${escapeHtml(drink.name)}</strong><small>${getRefillAmount(drink)} bijvullen (${drink.cellarStock} op voorraad)</small></span></label>`).join(''); content = rows ? `<p class="muted">Vink aan wat je hebt bijgevuld:</p>${rows}` : '<p class="muted">Geen dranken hoeven bijgevuld te worden.</p>'; }
  fields.innerHTML = content; $('#modal-title').innerHTML = title; $('#modal-form').querySelector('button[type="submit"]').textContent = mode === 'password' ? 'Inloggen' : mode === 'customer-order' ? 'Bestelling bevestigen' : mode === 'customer-history' ? 'Sluiten' : 'Opslaan'; const first = fields.querySelector('input'); if (first) first.focus(); }
function closeModal() { $('#modal').classList.add('is-hidden'); modalMode = null; modalData = {}; }
function renderHome(target = '#customers-list', customerIds = null) { const list = $(target); if (!list) return; list.innerHTML = ''; let customers = state.customers.filter((customer) => !customerIds || customerIds.includes(customer.id)); customers.sort((a, b) => isHome(a) ? -1 : isHome(b) ? 1 : (b.lastOrderAt || 0) - (a.lastOrderAt || 0)); if ($('#customer-count')) $('#customer-count').textContent = customers.length; $('#empty-state').classList.toggle('is-hidden', customers.length > 0); customers.forEach((customer) => { const button = document.createElement('button'); button.className = 'customer-card'; button.dataset.customerId = customer.id; button.innerHTML = `<strong>${escapeHtml(customer.name)}</strong>${isHome(customer) ? '' : `<span class="customer-balance ${customer.balance < 0 ? 'negative' : ''}">${formatMoney(customer.balance)}</span>`}`; list.appendChild(button); }); }
function renderGroups() { const list = $('#groups-list'); list.innerHTML = ''; state.groups.forEach((group) => { const button = document.createElement('button'); button.className = 'group-row'; button.dataset.groupId = group.id; button.innerHTML = `<strong>${escapeHtml(group.name)}</strong><span>${group.customerIds.length} klanten ›</span>`; list.appendChild(button); }); }
function renderGroup() { const group = getGroup(activeGroupId); if (!group) return; $('#group-title').textContent = group.name; $('#group-lock').textContent = groupLocked ? '[LOCK]' : '[OPEN]'; $('#group-lock').setAttribute('aria-label', groupLocked ? 'Groep ontgrendelen' : 'Groep vergrendelen'); $('.group-back').classList.toggle('is-hidden', groupLocked); renderHome('#group-customers', group.customerIds); }
function renderAssortment() { const list = $('#settings-list'); list.innerHTML = ''; state.drinks.forEach((drink) => { const row = document.createElement('div'); row.className = 'setting-row'; row.innerHTML = `<strong>${escapeHtml(drink.name)}</strong><span class="setting-price">${formatMoney(drink.price)}</span><button class="small-button" data-drink-action="edit" data-drink-id="${drink.id}" aria-label="${escapeHtml(drink.name)} bewerken">EDIT</button><button class="small-button danger" data-drink-action="delete" data-drink-id="${drink.id}" aria-label="${escapeHtml(drink.name)} verwijderen">X</button>`; list.appendChild(row); }); }
function renderInventory() { const list = $('#inventory-list'); list.innerHTML = ''; state.drinks.forEach((drink) => { const row = document.createElement('div'); row.className = 'inventory-row'; row.innerHTML = `<strong>${escapeHtml(drink.name)}</strong><label>In koelkast<input type="number" min="0" step="1" value="${drink.fridgeStock}" data-fridge-stock-id="${drink.id}" aria-label="In koelkast ${escapeHtml(drink.name)}"></label><label>Op voorraad<input type="number" min="0" step="1" value="${drink.cellarStock}" data-cellar-stock-id="${drink.id}" aria-label="Op voorraad ${escapeHtml(drink.name)}"></label><label>Max koelkast<input type="number" min="0" step="1" value="${drink.fridgeCapacity}" data-fridge-capacity-id="${drink.id}" aria-label="Maximaal in koelkast ${escapeHtml(drink.name)}"></label>`; list.appendChild(row); }); }
function renderCustomersAdmin() { const list = $('#admin-customers-list'); list.innerHTML = ''; state.customers.filter((customer) => !isHome(customer)).sort((a, b) => a.name.localeCompare(b.name, 'nl', { sensitivity: 'base' })).forEach((customer) => { const row = document.createElement('div'); row.className = 'setting-row'; row.innerHTML = `<strong>${escapeHtml(customer.name)}</strong><span class="setting-price">${formatMoney(customer.balance)}</span><button class="small-button" data-customer-action="edit" data-customer-id="${customer.id}" aria-label="Klant bewerken">EDIT</button><button class="small-button danger" data-customer-action="delete" data-customer-id="${customer.id}" aria-label="Klant verwijderen">X</button>`; list.appendChild(row); }); renderAdminGroups(); }
function renderAdminGroups() { const list = $('#admin-groups-list'); list.innerHTML = '<h3 class="list-heading">Groepen</h3>'; state.groups.forEach((group) => { const row = document.createElement('div'); row.className = 'setting-row'; row.innerHTML = `<strong>${escapeHtml(group.name)}</strong><span>${group.customerIds.length} klanten</span><button class="small-button" data-group-action="members" data-group-id="${group.id}" aria-label="Groepsleden beheren">✎</button><button class="small-button danger" data-group-action="delete" data-group-id="${group.id}" aria-label="Groep verwijderen">×</button>`; list.appendChild(row); }); }
function renderHistory() { const search = ($('#history-search')?.value || '').toLowerCase(); const dateFilter = $('#history-date')?.value || 'all'; const start = dateFilter === 'today' ? todayStart() : dateFilter === 'week' ? Date.now() - 7 * 86400000 : 0; const list = $('#history-list'); list.innerHTML = ''; state.history.filter((entry) => (!search || entry.customerName.toLowerCase().includes(search)) && entry.createdAt >= start).sort((a, b) => b.createdAt - a.createdAt).forEach((entry) => { const row = document.createElement('div'); row.className = 'history-row'; row.innerHTML = `<div><strong>${escapeHtml(entry.customerName)}</strong><span>${escapeHtml(entry.type === 'order' ? `${entry.quantity} x ${entry.drinkName}` : getHistoryLabel(entry))}</span></div><time>${new Date(entry.createdAt).toLocaleString('nl-NL')}</time><b class="${entry.type === 'deposit' ? 'positive' : 'negative'}">${getHistorySign(entry)}${formatMoney(entry.amount)}</b>`; list.appendChild(row); }); if (!list.children.length) list.innerHTML = '<p class="empty-order">Geen transacties gevonden.</p>'; }
function renderBalances() { const list = $('#balances-list'); list.innerHTML = ''; state.customers.filter((customer) => !isHome(customer)).sort((a, b) => a.name.localeCompare(b.name, 'nl', { sensitivity: 'base' })).forEach((customer) => { const row = document.createElement('div'); row.className = 'balance-row'; row.dataset.balanceCustomer = customer.id; row.innerHTML = `<div><strong>${escapeHtml(customer.name)}</strong><span class="${customer.balance < 0 ? 'negative' : ''}">${formatMoney(customer.balance)}</span></div><div class="balance-actions"><button class="secondary-button compact-button" data-action="deposit" data-customer-id="${customer.id}">Bedrag toevoegen</button><button class="secondary-button compact-button" data-action="withdrawal" data-customer-id="${customer.id}">Bedrag afhalen</button></div>`; list.appendChild(row); }); }
function renderStats() { const list = $('#stats-list'); const filters = $('#stats-filters'); if (!list || !filters) return; const people = state.customers.filter((customer) => !isHome(customer)).sort((a, b) => a.name.localeCompare(b.name, 'nl', { sensitivity: 'base' })); if (activeStatsCustomerId !== 'all' && !people.some((customer) => customer.id === activeStatsCustomerId)) activeStatsCustomerId = 'all'; filters.innerHTML = `<button class="stats-filter ${activeStatsCustomerId === 'all' ? 'is-active' : ''}" data-stat-filter="all">Algemeen</button>${people.map((customer) => `<button class="stats-filter ${activeStatsCustomerId === customer.id ? 'is-active' : ''}" data-stat-filter="${customer.id}">${escapeHtml(customer.name)}</button>`).join('')}`; const orders = state.history.filter((entry) => entry.type === 'order' && (activeStatsCustomerId === 'all' || entry.customerId === activeStatsCustomerId)); const counts = orders.reduce((result, entry) => { result[entry.drinkName] = (result[entry.drinkName] || 0) + entry.quantity; return result; }, {}); const topDrink = Object.entries(counts).sort((a, b) => b[1] - a[1])[0]; if (!topDrink) { list.innerHTML = '<p class="muted">Nog geen verkochte drankjes.</p>'; return; } if (activeStatsCustomerId !== 'all') { const rows = Object.entries(counts).sort((a, b) => b[1] - a[1]).map(([name, quantity]) => `<div class="leaderboard-row"><span>${escapeHtml(name)}</span><strong>${quantity}</strong></div>`).join(''); list.innerHTML = `<h3>Meest gekocht door deze klant</h3>${rows}`; return; } const leaderboard = state.history.filter((entry) => entry.type === 'order' && entry.drinkName === topDrink[0]).reduce((result, entry) => { result[entry.customerName] = (result[entry.customerName] || 0) + entry.quantity; return result; }, {}); const rows = Object.entries(leaderboard).sort((a, b) => b[1] - a[1]).map(([name, quantity], index) => `<div class="leaderboard-row"><span>${index + 1}. ${escapeHtml(name)}</span><strong>${quantity}</strong></div>`).join(''); list.innerHTML = `<div class="stat-card"><span>Meest verkocht</span><strong>${escapeHtml(topDrink[0])}</strong><span>${topDrink[1]} verkocht</span></div><h3>Leaderboard voor ${escapeHtml(topDrink[0])}</h3>${rows}`; }
function isLowStock(drink) { const threshold = drink.fridgeCapacity > 0 ? Math.max(1, Math.floor(drink.fridgeCapacity * 0.2)) : 1; return drink.fridgeStock <= threshold; }
function showLowStockWarning(drinks) { const warning = $('#low-stock-warning'); const lowStockDrinks = [...new Set(drinks.filter(isLowStock).map((drink) => `${drink.name} (${drink.fridgeStock})`))]; if (!warning || !lowStockDrinks.length) return; warning.textContent = `Bijna op: ${lowStockDrinks.join(', ')} in de koelkast`; warning.classList.add('is-visible'); clearTimeout(lowStockTimer); lowStockTimer = setTimeout(() => warning.classList.remove('is-visible'), 8000); }
function renderAll() { renderHome(); renderGroups(); renderAssortment(); renderInventory(); renderCustomersAdmin(); renderHistory(); renderBalances(); renderStats(); }
function addOrder(customer, selections) { const now = Date.now(); let total = 0; selections.forEach(({ drink, quantity }) => { const amount = drink.price * quantity; total += amount; drink.fridgeStock = Math.max(0, drink.fridgeStock - quantity); state.history.push({ id: makeId('history'), type: 'order', customerId: customer.id, customerName: customer.name, drinkName: drink.name, quantity, amount, createdAt: now }); }); if (!isHome(customer)) { customer.balance -= total; customer.lastOrderAt = now; } saveState(); renderAll(); closeModal(); showToast('Bestelling toegevoegd.'); showLowStockWarning(selections.map(({ drink }) => drink)); }
function submitModal(event) { event.preventDefault(); const error = $('#modal-error'); error.textContent = '';
  if (modalMode === 'password') { if ($('#modal-password').value !== ADMIN_PASSWORD) { error.textContent = 'Onjuist wachtwoord. Probeer opnieuw.'; $('#modal-password').focus(); return; } if (modalData.unlock) groupLocked = false; else if (modalData.lock) groupLocked = true; else { adminUnlocked = true; refreshAdminSession(); showView('admin-view'); } closeModal(); if (activeGroupId) renderGroup(); return; }
  if (modalMode === 'customer-history') { closeModal(); return; }
  if (modalMode === 'customer-order') { const selections = state.drinks.map((drink) => ({ drink, quantity: Number($(`#pick-${drink.id}`)?.textContent || 0) })).filter((item) => item.quantity > 0); if (!selections.length) { error.textContent = 'Kies minimaal een drankje.'; return; } addOrder(modalData.customer, selections); return; }
  if (modalMode === 'drink') { const name = $('#modal-name').value.trim(); const price = parsePrice($('#modal-price').value); if (!name || !price) { error.textContent = 'Vul een naam en geldige prijs in.'; return; } if (modalData.drink) Object.assign(modalData.drink, { name, price }); else state.drinks.push({ id: makeId('drink'), name, price, fridgeStock: 0, cellarStock: 0, fridgeCapacity: 0 }); saveState(); closeModal(); renderAll(); return; }
  if (modalMode === 'customer') { const name = $('#modal-name').value.trim(); if (!name) return; if (modalData.customer) modalData.customer.name = name; else state.customers.push({ id: makeId('customer'), name, balance: 0, lastOrderAt: 0 }); saveState(); closeModal(); renderAll(); return; }
  if (modalMode === 'deposit' || modalMode === 'withdrawal') { const amount = parsePrice($('#modal-price').value); if (!amount) { error.textContent = 'Vul een geldig bedrag in.'; return; } const customer = modalData.customer; customer.balance += modalMode === 'deposit' ? amount : -amount; state.history.push({ id: makeId('history'), type: modalMode, customerId: customer.id, customerName: customer.name, amount, quantity: 1, createdAt: Date.now() }); saveState(); closeModal(); renderAll(); showToast(modalMode === 'deposit' ? 'Bijstorting verwerkt.' : 'Bedrag afgehaald.'); return; }
  if (modalMode === 'group') { const name = $('#modal-name').value.trim(); if (!name) return; if (modalData.group) { modalData.group.name = name; saveState(); closeModal(); renderAll(); } else { const group = { id: makeId('group'), name, customerIds: [] }; state.groups.push(group); saveState(); openModal('group-members', { group }); } return; }
  if (modalMode === 'group-members') { const group = modalData.group; group.customerIds = [...document.querySelectorAll('[data-member-id]:checked')].map((input) => input.dataset.memberId); saveState(); closeModal(); renderAll(); return; }
  if (modalMode === 'refill') { document.querySelectorAll('[data-refill-id]:checked').forEach((input) => { const drink = state.drinks.find((entry) => entry.id === input.dataset.refillId); const amount = drink ? getRefillAmount(drink) : 0; if (drink) { drink.fridgeStock += amount; drink.cellarStock -= amount; } }); state.drinks.forEach((drink) => { drink.refillBaseline = drink.fridgeStock; }); state.lastRefillAt = Date.now(); saveState(); closeModal(); renderInventory(); showToast('Hervulling opgeslagen.'); }
}
const ADMIN_VIEW_IDS = ['admin-view', 'inventory-view', 'assortment-view', 'customers-view', 'history-view', 'balances-view', 'stats-view'];
function isAdminViewVisible() { return ADMIN_VIEW_IDS.some((viewId) => !document.getElementById(viewId).classList.contains('is-hidden')); }
function refreshAdminSession() { clearTimeout(adminUnlockTimer); clearTimeout(adminIdleTimer); adminUnlockTimer = setTimeout(() => { adminUnlocked = false; if (isAdminViewVisible()) showView('home-view'); }, 120000); adminIdleTimer = setTimeout(() => { adminUnlocked = false; if (isAdminViewVisible()) showView('home-view'); }, 120000); }
function openAdmin() { if (adminUnlocked) { refreshAdminSession(); showView('admin-view'); } else openModal('password'); }
function goAdminView(view) { if (!adminUnlocked) return openAdmin(); refreshAdminSession(); showView(`${view}-view`); if (view === 'history') renderHistory(); if (view === 'stats') renderStats(); }

document.addEventListener('click', (event) => {
  const actionElement = event.target.closest('[data-action]'); const action = actionElement?.dataset.action; const customerCard = event.target.closest('.customer-card'); const groupRow = event.target.closest('.group-row'); const adminCard = event.target.closest('[data-admin-view]');
  if (action === 'admin-home') { if (!adminUnlocked) return openAdmin(); refreshAdminSession(); }
  if (action === 'admin') return openAdmin(); if (action === 'close-modal') return closeModal(); if (action === 'home') { if (!groupLocked) { showView('home-view'); renderHome(); } return; } if (action === 'admin-home') return showView('admin-view'); if (action === 'add-drink') return openModal('drink'); if (action === 'add-customer') return openModal('customer'); if (action === 'new-group') return openModal('group'); if (action === 'manage-groups') return renderAdminGroups(); if (action === 'refill') return openModal('refill'); if (action === 'deposit' || action === 'withdrawal') return openModal(action, { customer: getCustomer(actionElement.dataset.customerId) });
  if (action === 'toggle-group-lock') return openModal('password', { lock: !groupLocked, unlock: groupLocked });
  const statsFilter = event.target.closest('[data-stat-filter]'); if (statsFilter) { activeStatsCustomerId = statsFilter.dataset.statFilter; renderStats(); return; }
  if (adminCard) return goAdminView(adminCard.dataset.adminView); if (customerCard) return openModal('customer-order', { customer: getCustomer(customerCard.dataset.customerId) });
  const balanceCustomer = event.target.closest('[data-balance-customer]'); if (balanceCustomer && !event.target.closest('[data-action="deposit"]')) return openModal('customer-history', { customer: getCustomer(balanceCustomer.dataset.balanceCustomer) });
  if (groupRow) { activeGroupId = groupRow.dataset.groupId; groupLocked = false; renderGroup(); showView('group-view'); return; }
  const picker = event.target.closest('[data-picker]'); if (picker) { const value = $(`#pick-${picker.dataset.drinkId}`); value.textContent = Math.max(0, Number(value.textContent) + (picker.dataset.picker === 'up' ? 1 : -1)); return; }
  const drinkAction = event.target.closest('[data-drink-action]'); if (drinkAction) { const drink = state.drinks.find((item) => item.id === drinkAction.dataset.drinkId); if (drinkAction.dataset.drinkAction === 'edit') openModal('drink', { drink }); else if (confirm(`'${drink.name}' verwijderen?`)) { state.drinks = state.drinks.filter((item) => item.id !== drink.id); saveState(); renderAll(); } return; }
  const customerAction = event.target.closest('[data-customer-action]'); if (customerAction) { const customer = getCustomer(customerAction.dataset.customerId); if (customerAction.dataset.customerAction === 'edit') openModal('customer', { customer }); else if (confirm(`'${customer.name}' verwijderen?`)) { state.customers = state.customers.filter((item) => item.id !== customer.id); state.groups.forEach((group) => { group.customerIds = group.customerIds.filter((id) => id !== customer.id); }); saveState(); renderAll(); } return; }
  const groupAction = event.target.closest('[data-group-action]'); if (groupAction) { const group = getGroup(groupAction.dataset.groupId); if (groupAction.dataset.groupAction === 'members') openModal('group-members', { group }); else if (confirm(`Groep '${group.name}' verwijderen?`)) { state.groups = state.groups.filter((item) => item.id !== group.id); saveState(); renderAll(); } }
});
document.addEventListener('input', (event) => { const input = event.target; const drinkId = input.dataset.fridgeStockId || input.dataset.cellarStockId || input.dataset.fridgeCapacityId; if (drinkId) { const drink = state.drinks.find((item) => item.id === drinkId); if (drink) { if (input.dataset.fridgeStockId) drink.fridgeStock = parseCount(input.value); if (input.dataset.cellarStockId) drink.cellarStock = parseCount(input.value); if (input.dataset.fridgeCapacityId) drink.fridgeCapacity = parseCount(input.value); saveState(); } } if (input.id === 'history-search') renderHistory(); });
$('#history-date').addEventListener('change', renderHistory); $('#modal-form').addEventListener('submit', submitModal); $('#modal').addEventListener('click', (event) => { if (event.target.id === 'modal') closeModal(); });
['pointerdown', 'keydown', 'input', 'scroll'].forEach((eventName) => document.addEventListener(eventName, () => { if (adminUnlocked && isAdminViewVisible()) refreshAdminSession(); }, { passive: eventName === 'scroll' }));
renderAll(); $('#app-version').textContent = `v${APP_VERSION}`; if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('./service-worker.js', { updateViaCache: 'none' }).then((registration) => registration.update()).catch((error) => console.warn('Offline-modus kon niet worden geactiveerd.', error)));
